# Generated by Django 5.2.3 on 2025-06-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_dietician',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
